### ISSUE TITLE
Make it work with Activity

### ISSUE THREAD

**Issue by soareseneves** [florent37/NoActivityResult#3]
Hey there,

Can you make this work with Activity? Currently it only works with AppCompatActivity and FragmentActivity.

Thanks.

**Comment by Ztiany** [comment]
@soareseneves Read the source, you will find that it can only work with with AppCompatActivity and FragmentActivity.

**Comment by victor-denisenko** [comment]
Hi, 

No. The library need FragmentManager instance from activity, but Activity#getFragmentManager() is deprecated. So lib use FragmentActivity#getSupportFragmentManager().
