### ISSUE TITLE
Make it work without Activity (but with Context)

### ISSUE THREAD

**Issue by whalemare** [florent37/NoActivityResult#4]
Hi, thanks for your library.

Can you add feature for support start activity for result only with context, without activity or fragment? Useful for quickly access to other libraries, that depend on activityForResult behavior. 
If you don't mind, I could create a PR with this feature

**Comment by iamareebjamal** [comment]
Not sure how it'll work with just context as startActivityForResult requires activity semantics

**Comment by florent37** [comment]
Not possible because it needs to add a fragment that manage the activity result
